name: Generate API client 🔀

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  generate:
    name: Run generator 🔬
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Download OpenAPI spec 📥
        run: |
          curl -s -o openapi.yaml https://raw.githubusercontent.com/FIS2425/api-gateway/refs/heads/main/static/openapi.yaml

      - name: Generate API client 🚀
        uses: docker://openapitools/openapi-generator-cli:latest-release
        env:
          TS_POST_PROCESS_FILE: true
        with:
          args: >-
            generate -i openapi.yaml
            -g typescript-axios --additional-properties=npmName=@cloudmedix/apiclient
            --additional-properties=supportsES6=true
            --additional-properties=useSingleRequestParameter=true
            --additional-properties=stringEnums=true
            --enable-post-process-file
            -o /src

      - name: Check if .ts files have changed 🧐
        id: diff
        run: echo "count=$(git status -su | grep ts | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit changes 📝
        if: ${{ steps.diff.outputs.count > 0 }}
        run: |
          git config user.name GitHub Actions
          git config user.email action@github.com
          git config pull.rebase true
          git config rebase.autoStash true
          git pull
          git add src/*.ts
          git commit -m "ci: update apiclient" -m "" -m "Run id: ${{ github.run_id }}" || echo
          git push
